#!/usr/bin/env node

/**
 * 🔐 SECRET ROTATOR — Rotación de secretos API con vault local
 * 
 * Uso:
 *   node scripts/secret-rotator.js list              # Listar secretos
 *   node scripts/secret-rotator.js rotate alibaba    # Rotar uno
 *   node scripts/secret-rotator.js rotate --all      # Rotar todos
 *   node scripts/secret-rotator.js verify            # Verificar vault
 *   node scripts/secret-rotator.js export --env      # Exportar como .env
 * 
 * SEGURIDAD: El vault se cifra con AES-256-GCM.
 * La master key se deriva de una passphrase + salt.
 * 
 * Variables de entorno:
 *   VAULT_PASSPHRASE   - Passphrase maestra (obligatoria)
 */

const crypto = require('crypto');
const fs = require('fs');
const path = require('path');

const VAULT_DIR = path.join(__dirname, '..', 'vault');
const VAULT_FILE = path.join(VAULT_DIR, 'secrets.enc');
const VAULT_META = path.join(VAULT_DIR, 'metadata.json');
const ALGORITHM = 'aes-256-gcm';
const KEY_LENGTH = 32;
const IV_LENGTH = 16;
const SALT_LENGTH = 32;
const TAG_LENGTH = 16;
const ITERATIONS = 100000;

// ─── CIFRADO ────────────────────────────────────────────────────────────────
function deriveKey(passphrase, salt) {
  return crypto.pbkdf2Sync(passphrase, salt, ITERATIONS, KEY_LENGTH, 'sha512');
}

function encrypt(plaintext, passphrase) {
  const salt = crypto.randomBytes(SALT_LENGTH);
  const key = deriveKey(passphrase, salt);
  const iv = crypto.randomBytes(IV_LENGTH);
  const cipher = crypto.createCipheriv(ALGORITHM, key, iv);
  
  let encrypted = cipher.update(plaintext, 'utf8', 'hex');
  encrypted += cipher.final('hex');
  const tag = cipher.getAuthTag();
  
  return {
    salt: salt.toString('hex'),
    iv: iv.toString('hex'),
    data: encrypted,
    tag: tag.toString('hex')
  };
}

function decrypt(encryptedObj, passphrase) {
  const salt = Buffer.from(encryptedObj.salt, 'hex');
  const key = deriveKey(passphrase, salt);
  const iv = Buffer.from(encryptedObj.iv, 'hex');
  const tag = Buffer.from(encryptedObj.tag, 'hex');
  
  const decipher = crypto.createDecipheriv(ALGORITHM, key, iv);
  decipher.setAuthTag(tag);
  
  let decrypted = decipher.update(encryptedObj.data, 'hex', 'utf8');
  decrypted += decipher.final('utf8');
  
  return decrypted;
}

// ─── VAULT ──────────────────────────────────────────────────────────────────
class SecretVault {
  constructor(passphrase) {
    this.passphrase = passphrase;
    this.secrets = {};
    this.metadata = {};
    fs.mkdirSync(VAULT_DIR, { recursive: true });
    this._load();
  }
  
  _load() {
    if (fs.existsSync(VAULT_FILE)) {
      try {
        const encrypted = JSON.parse(fs.readFileSync(VAULT_FILE, 'utf-8'));
        const decrypted = decrypt(encrypted, this.passphrase);
        this.secrets = JSON.parse(decrypted);
      } catch (err) {
        console.error('❌ Error descifrando vault. ¿Passphrase correcta?');
        process.exit(1);
      }
    }
    
    if (fs.existsSync(VAULT_META)) {
      this.metadata = JSON.parse(fs.readFileSync(VAULT_META, 'utf-8'));
    }
  }
  
  _save() {
    const plaintext = JSON.stringify(this.secrets);
    const encrypted = encrypt(plaintext, this.passphrase);
    fs.writeFileSync(VAULT_FILE, JSON.stringify(encrypted, null, 2));
    
    this.metadata.lastModified = new Date().toISOString();
    this.metadata.secretCount = Object.keys(this.secrets).length;
    fs.writeFileSync(VAULT_META, JSON.stringify(this.metadata, null, 2));
  }
  
  set(key, value, provider) {
    this.secrets[key] = {
      value,
      provider,
      createdAt: this.secrets[key]?.createdAt || new Date().toISOString(),
      rotatedAt: new Date().toISOString(),
      version: (this.secrets[key]?.version || 0) + 1
    };
    this._save();
    console.log(`  ✅ ${key} guardado (v${this.secrets[key].version})`);
  }
  
  get(key) {
    return this.secrets[key]?.value;
  }
  
  list() {
    return Object.entries(this.secrets).map(([key, data]) => ({
      key,
      provider: data.provider,
      version: data.version,
      rotatedAt: data.rotatedAt,
      masked: data.value.slice(0, 4) + '****' + data.value.slice(-4)
    }));
  }
  
  delete(key) {
    delete this.secrets[key];
    this._save();
  }
  
  exportEnv() {
    let env = '# Generated by secret-rotator.js\n';
    env += `# Date: ${new Date().toISOString()}\n\n`;
    
    for (const [key, data] of Object.entries(this.secrets)) {
      const envKey = key.toUpperCase().replace(/[^A-Z0-9_]/g, '_');
      env += `${envKey}=${data.value}\n`;
    }
    
    return env;
  }
}

// ─── ROTACIÓN POR PROVEEDOR ─────────────────────────────────────────────────
const rotators = {
  alibaba: {
    name: 'Alibaba Cloud / DashScope',
    instructions: [
      '1. Ve a https://dashscope.console.aliyun.com/',
      '2. API Key Management > Create New Key',
      '3. Copia la nueva key',
      '4. Ejecuta: node secret-rotator.js set alibaba_key <NUEVA_KEY>'
    ],
    envVar: 'ALIBABA_API_KEY'
  },
  huggingface: {
    name: 'HuggingFace',
    instructions: [
      '1. Ve a https://huggingface.co/settings/tokens',
      '2. Create new token (role: read)',
      '3. Copia el token',
      '4. Ejecuta: node secret-rotator.js set hf_token <NUEVO_TOKEN>'
    ],
    envVar: 'HF_TOKEN'
  },
  openrouter: {
    name: 'OpenRouter',
    instructions: [
      '1. Ve a https://openrouter.ai/keys',
      '2. Create new key',
      '3. Copia la key',
      '4. Ejecuta: node secret-rotator.js set openrouter_key <NUEVA_KEY>'
    ],
    envVar: 'OPENROUTER_API_KEY'
  },
  groq: {
    name: 'Groq',
    instructions: [
      '1. Ve a https://console.groq.com/keys',
      '2. Create API Key',
      '3. Copia la key',
      '4. Ejecuta: node secret-rotator.js set groq_key <NUEVA_KEY>'
    ],
    envVar: 'GROQ_API_KEY'
  }
};

// ─── CLI ────────────────────────────────────────────────────────────────────
function main() {
  const args = process.argv.slice(2);
  const passphrase = process.env.VAULT_PASSPHRASE;
  
  if (!passphrase) {
    console.error('❌ VAULT_PASSPHRASE no configurada');
    console.error('   Exporta: export VAULT_PASSPHRASE="tu-passphrase-segura"');
    process.exit(1);
  }
  
  if (args.includes('--help') || args.length === 0) {
    console.log(`
Secret Rotator — Pedro Belentani
Vault cifrado AES-256-GCM

Uso:
  node secret-rotator.js list                    Listar secretos
  node secret-rotator.js set <key> <value>       Guardar secreto
  node secret-rotator.js get <key>               Obtener secreto
  node secret-rotator.js delete <key>            Eliminar secreto
  node secret-rotator.js rotate <provider>       Guía de rotación
  node secret-rotator.js verify                  Verificar vault
  node secret-rotator.js export --env            Exportar como .env
  node secret-rotator.js providers               Proveedores disponibles

Proveedores: alibaba, huggingface, openrouter, groq
`);
    return;
  }
  
  const vault = new SecretVault(passphrase);
  const command = args[0];
  
  switch (command) {
    case 'list':
      console.log('\n🔐 Secretos en vault:\n');
      const list = vault.list();
      if (list.length === 0) {
        console.log('   (vacío)');
      } else {
        list.forEach(s => {
          console.log(`   ${s.key.padEnd(25)} ${s.provider.padEnd(15)} v${s.version}  ${s.masked}`);
        });
      }
      break;
      
    case 'set':
      if (args.length < 3) {
        console.error('Uso: set <key> <value>');
        return;
      }
      vault.set(args[1], args[2], args[1].split('_')[0]);
      break;
      
    case 'get':
      const val = vault.get(args[1]);
      if (val) console.log(val);
      else console.log('No encontrado');
      break;
      
    case 'delete':
      vault.delete(args[1]);
      console.log(`🗑️  ${args[1]} eliminado`);
      break;
      
    case 'rotate':
      const provider = args[1];
      if (provider === '--all') {
        console.log('\n🔄 Rotación de todos los proveedores:\n');
        Object.entries(rotators).forEach(([key, p]) => {
          console.log(`\n  ${p.name}:`);
          p.instructions.forEach(i => console.log(`    ${i}`));
        });
      } else if (rotators[provider]) {
        console.log(`\n🔄 Rotación: ${rotators[provider].name}\n`);
        rotators[provider].instructions.forEach(i => console.log(`  ${i}`));
      } else {
        console.log('Proveedor no encontrado. Usa: providers');
      }
      break;
      
    case 'providers':
      console.log('\n🏢 Proveedores configurables:\n');
      Object.entries(rotators).forEach(([key, p]) => {
        console.log(`  ${key.padEnd(15)} ${p.name} (env: ${p.envVar})`);
      });
      break;
      
    case 'verify':
      try {
        const testEncrypt = encrypt('test', passphrase);
        const testDecrypt = decrypt(testEncrypt, passphrase);
        if (testDecrypt === 'test') {
          console.log('✅ Vault operativo — cifrado/descifrado verificado');
          console.log(`   Secretos: ${vault.list().length}`);
          console.log(`   Última modificación: ${vault.metadata.lastModified || 'nunca'}`);
        }
      } catch (err) {
        console.error('❌ Error de verificación:', err.message);
      }
      break;
      
    case 'export':
      if (args.includes('--env')) {
        const envContent = vault.exportEnv();
        const envFile = path.join(VAULT_DIR, '.env.generated');
        fs.writeFileSync(envFile, envContent);
        console.log(`📄 .env generado: ${envFile}`);
        console.log('⚠️  Asegúrate de NO commitear este archivo');
      }
      break;
      
    default:
      console.log('Comando no reconocido. Usa --help');
  }
}

main();

module.exports = { SecretVault, encrypt, decrypt };
